development:
  adapter: postgresql
  encoding: unicode
  database: redtix_development
  pool: 5
  username: redtix
  password:
  host: localhost
  port: 5432

test: &test
  adapter: postgresql
  encoding: unicode
  database: redtix_test
  pool: 5
  username: redtix
  password:
  host: localhost
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: ENV['DATABASE_NAME']
  pool: 5
  username: ENV['DATABASE_USERNAME']
  password: ENV['DATABASE_PASSWORD']
  host: ENV['DATABASE_HOST']
  port: ENV['DATABASE_PORT']

cucumber:
  <<: *test